// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BirthInfo struct {
	Date          string  `json:"date"`
	City          *string `json:"city"`
	StateProvince *string `json:"stateProvince"`
	Country       string  `json:"country"`
}

type Captaincy struct {
	Captain   bool `json:"captain"`
	Assistant bool `json:"assistant"`
}

type Conference struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	NameShort    string `json:"nameShort"`
	Abbreviation string `json:"abbreviation"`
	Active       bool   `json:"active"`
}

type Division struct {
	ID           int         `json:"id"`
	Name         string      `json:"name"`
	NameShort    string      `json:"nameShort"`
	Abbreviation string      `json:"abbreviation"`
	Conference   *Conference `json:"conference"`
	Active       bool        `json:"active"`
}

type Franchise struct {
	ID               int    `json:"id"`
	TeamName         string `json:"teamName"`
	LocationName     string `json:"locationName"`
	FirstSeasonID    int    `json:"firstSeasonId"`
	MostRecentTeamID int    `json:"mostRecentTeamId"`
}

type Name struct {
	First string `json:"first"`
	Last  string `json:"last"`
}

type Player struct {
	ID            int        `json:"id"`
	Name          *Name      `json:"name"`
	Number        int        `json:"number"`
	Position      *Position  `json:"position"`
	Age           int        `json:"age"`
	Height        string     `json:"height"`
	Weight        int        `json:"weight"`
	Nationality   string     `json:"nationality"`
	Birth         *BirthInfo `json:"birth"`
	Captaincy     *Captaincy `json:"captaincy"`
	Rookie        bool       `json:"rookie"`
	ShootsCatches string     `json:"shootsCatches"`
	RosterStatus  string     `json:"rosterStatus"`
	CurrentTeam   *Team      `json:"currentTeam"`
	Active        bool       `json:"active"`
}

type Position struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Abbreviation string `json:"abbreviation"`
}

type Team struct {
	ID              int        `json:"id"`
	Name            string     `json:"name"`
	TeamName        string     `json:"teamName"`
	ShortName       string     `json:"shortName"`
	Abbreviation    string     `json:"abbreviation"`
	LocationName    string     `json:"locationName"`
	Venue           *Venue     `json:"venue"`
	Division        *Division  `json:"division"`
	Franchise       *Franchise `json:"franchise"`
	FirstYearOfPlay string     `json:"firstYearOfPlay"`
	OfficialSiteURL string     `json:"officialSiteUrl"`
	Players         []*Player  `json:"players"`
	Active          bool       `json:"active"`
}

type Timezone struct {
	ID     string `json:"id"`
	Offset int    `json:"offset"`
	Tz     string `json:"tz"`
}

type Venue struct {
	Name     string    `json:"name"`
	City     string    `json:"city"`
	TimeZone *Timezone `json:"timeZone"`
}
