// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Conference struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	NameShort    string `json:"nameShort"`
	Abbreviation string `json:"abbreviation"`
	Active       bool   `json:"active"`
}

type Division struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	NameShort    string `json:"nameShort"`
	Abbreviation string `json:"abbreviation"`
	ConferenceID int    `json:"conference_id"`
	Active       bool   `json:"active"`
}

type Franchise struct {
	ID               int    `json:"id"`
	TeamName         string `json:"teamName"`
	LocationName     string `json:"locationName"`
	FirstSeasonID    int    `json:"firstSeasonId"`
	MostRecentTeamID int    `json:"mostRecentTeamId"`
}

type Player struct {
	ID                 int       `json:"id"`
	FullName           string    `json:"fullName"`
	FirstName          string    `json:"firstName"`
	LastName           string    `json:"lastName"`
	PrimaryNumber      string    `json:"primaryNumber"`
	CurrentAge         int       `json:"currentAge"`
	Height             string    `json:"height"`
	Weight             int       `json:"weight"`
	BirthDate          string    `json:"birthDate"`
	BirthCity          *string   `json:"birthCity"`
	BirthStateProvince *string   `json:"birthStateProvince"`
	BirthCountry       *string   `json:"birthCountry"`
	Nationality        string    `json:"nationality"`
	Active             bool      `json:"active"`
	Captain            *bool     `json:"captain"`
	AlternateCaptain   *bool     `json:"alternateCaptain"`
	ShootsCatches      string    `json:"shootsCatches"`
	RosterStatus       string    `json:"rosterStatus"`
	Rookie             bool      `json:"rookie"`
	CurrentTeam        *int      `json:"currentTeam"`
	Position           *Position `json:"position"`
}

type Position struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Abbreviation string `json:"abbreviation"`
}

type Team struct {
	ID              int       `json:"id"`
	Name            string    `json:"name"`
	TeamName        string    `json:"teamName"`
	ShortName       string    `json:"shortName"`
	Abbreviation    string    `json:"abbreviation"`
	LocationName    string    `json:"locationName"`
	FirstYearOfPlay int       `json:"firstYearOfPlay"`
	OfficialSiteURL string    `json:"officialSiteUrl"`
	VenueID         int       `json:"venue_id"`
	DivisionID      int       `json:"division_id"`
	ConferenceID    int       `json:"conference_id"`
	FranchiseID     int       `json:"franchise_id"`
	Roster          []*Player `json:"roster"`
	Active          bool      `json:"active"`
}

type Timezone struct {
	ID     string `json:"id"`
	Offset int    `json:"offset"`
	Tz     string `json:"tz"`
}

type Venue struct {
	ID         int       `json:"id"`
	Name       string    `json:"name"`
	City       *string   `json:"city"`
	TimeZone   *Timezone `json:"timeZone"`
	Appenabled *bool     `json:"appenabled"`
}
